DROP TABLE IF EXISTS "reserva_espacio" CASCADE;
DROP TABLE IF EXISTS "reserva" CASCADE;
DROP TABLE IF EXISTS "intervalos_disponibles" CASCADE;
DROP TABLE IF EXISTS "asignacion" CASCADE;
DROP TABLE IF EXISTS "espacio" CASCADE;
DROP TABLE IF EXISTS "persona" CASCADE;
